version: '3.8'

services:
  gateway:
    image: truongikpk/bookstore-api-gateway:v1.0.0
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - bookstore-network

networks:
  bookstore-network:
    name: bookstore-network