apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  SPRING_DATA_REDIS_HOST: "redis-bookstore-do-user-36177370-0.j.db.ondigitalocean.com"
  SPRING_DATA_REDIS_PORT: "25061"
  SPRING_DATA_REDIS_USERNAME: "default"
  SPRING_DATA_REDIS_SSL_ENABLED: "true"
